title: David's Test Blog
tagline: Testing Testing Testing
author :
  name : David Andrzejewski
  email : david.andrzej@gmail.com
  github : davidandrzej
  twitter : davidandrzej

navigation :
  - archive.html
  - tags.html
  - categories.html
  - about.md
  
