title: Bayes' Cave
tagline: Artisanal ones and zeros
author :
  name : David Andrzejewski
  email : david.andrzej@gmail.com
  github : davidandrzej
  twitter : davidandrzej

navigation :
  - archive.html
  - tags.html
  - categories.html
  - about.md
  
